Pirate.create(name: "Zanzibar", height: "tall", weight: "heavy")
Pirate.create(name: "Ba'althazar", height: "medium", weight: "heafty")
Pirate.create(name: "Berber", height: "short", weight: "light")

Ship.create(name: "HMS Beagle", typos: "Kutter", booty: "Science Stuff", pirate_id: 1)
Ship.create(name: "HMS Surprise", typos: "Man'O War", booty: "Cannons", pirate_id: 1)
Ship.create(name: "HMS Victory", typos: "Man'O War", booty: "Cannons", pirate_id: 2)
Ship.create(name: "USS Stannis", typos: "Carrier", booty: "F-18's", pirate_id: 2)
Ship.create(name: "USS McCain", typos: "Friggate", booty: "S2S Missiles", pirate_id: 2)
Ship.create(name: "USS Ohio", typos: "Sub", booty: "Nukes", pirate_id: 2)
Ship.create(name: "USS Virginia", typos: "Sub", booty: "S2S Missiles", pirate_id: 2)
Ship.create(name: "HMS Forestall", typos: "Carrier", booty: "F-4 Phantoms", pirate_id: 3)
